export const RES_MENU_REQUEST = " RES_MENU_REQUEST";
export const RES_MENU_LOADED = " RES_MENU_LOADED";
export const RES_MENU_FAILURE = "RES_MENU_FAILURE";
export const INCREASE_COUNT = "  INCREASE_COUNT";
export const DECREASE_COUNT = "  DECREASE_COUNT";
export const DELETE_ITEM = "  DELETE_ITEM";
export const ADD_TO_CART = "ADD_TO_CART";
